apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080  # This will make the app accessible on port 30080 